name: sequential_navigator
description: A new Flutter package project.
version: 0.0.3
repository: https://github.com/SexyBeast007/sequential_navigator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.0
  get: ^4.3.8
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  pull_to_refresh: ^2.0.0
  flutter_easyrefresh: ^2.2.1

dev_dependencies:
  hive_generator: ^1.1.1
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
 
  uses-material-design: true
